import os
print("testing")
print("Add Commit Push")
print("\n git status")
os.system("git status")
print("\n git add -A")
os.system("git add -A")
print('\n git commit -m "Update files."')
os.system('git commit -m "Update files."')
print("\n git push")
os.system("git push")